// Generated by Wrangler on Sat Mar 09 2024 00:43:28 GMT+0000 (Greenwich Mean Time)
// by running `wrangler types`

interface Env {
	KV: KVNamespace;
	ORIGIN: "https://webauthn.demo.paoloraez.dev";
}
