// Generated by Wrangler on Sat Mar 09 2024 23:05:03 GMT+0000 (Greenwich Mean Time)
// by running `wrangler types`

interface Env {
	KV: KVNamespace;
	JWT_SECRET: "cc7e0d44fd473002f1c42167459001140ac6389b7353f8088f4d9a95f2f596f2";
	ENVIRONMENT: string;
	ORIGIN: string;
}
